apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: books
  labels:
    app: books
spec:
  selector:
    matchLabels:
      app: books
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - image: peterhell95/books:jenkins
          imagePullPolicy: Always
          name: books
          ports:
            - containerPort: 8080
